---
stages:
  - test
  - build
  - upload
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  FILENAME: probe-$CI_COMMIT_TAG.tar.gz
  DEST:  $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/probe/$CI_COMMIT_TAG/probe-$CI_COMMIT_TAG.tar.gz


clippy:
  image: rust:latest
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    
fmt:
  image: rust:latest
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

build:
  stage: build
  tags:
    - docker
  image: messense/cargo-zigbuild:latest
  script:
    - cargo build --release
    - tar czf probe.tar.gz -C target/release probe
  cache:
    paths:
      - target
      - .cargo

  artifacts:
    paths:
      - probe.tar.gz


upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - mv probe.tar.gz $FILENAME
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $FILENAME $DEST
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - build

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"$FILENAME\",\"url\":\"$DEST\"}" \
        --description "./Changelog.md"
