---
stages:
  - build
  - upload
  - deploy

variables:
  FILENAME: "probe-$CI_COMMIT_TAG.tar.gz"
  DEST:  "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/probe/${CI_COMMIT_TAG}/$FILENAME"

build:
  stage: build
  tags:
    - docker
  image: centos:7
  before_script:
    - yum -y update
    - yum -y install curl cmake
    - yum -y group install "Development Tools"
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $HOME/.cargo/env
  script:
    - cargo build --release
    - tar czf probe.tar.gz -C target/release probe
  artifacts:
    paths:
      - probe.tar.gz


upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${FILENAME} ${DEST}
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - build

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${FILENAME}\",\"url\":\"${DEST}\"}" \
        --description "./Changelog.md"
