[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 1"
#[[probes.filters]]
#name = "Foo"
#pattern = "123"
#[[probes.filters]]
#name = "Bar"
#pattern = "456"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 2"
[[probes]]
address = "tcp://127.0.0.1:5558"
name = "Probe 3"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 4"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 5"
[[probes]]
address = "tcp://127.0.0.1:5555"
name = "Probe 6"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 7"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 8"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 9"
[[probes]]
address = "tcp://127.0.0.1:5556"
name = "Probe 10"
