[[probes]]
address = "127.0.0.1:5556"
mode = "zmq"
name = "Probe 1"
count = 3
#[[probes.filters]]
#name = "Foo"
#pattern = "123"
#count = 8
#[[probes.filters]]
#name = "Bar"
#pattern = "456"
#count = 7
