[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 1"
count = 0
#[[probes.filters]]
#name = "Foo"
#pattern = "123"
#count = 0
#[[probes.filters]]
#name = "Bar"
#pattern = "456"
#count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 2"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5558"
mode = "zmq"
name = "Probe 3"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 4"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 5"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5555"
mode = "zmq"
name = "Probe 6"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 7"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 8"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 9"
count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 10"
count = 0
