[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 1"
count = 0
#[[probes.filters]]
#name = "Foo"
#pattern = "123"
#count = 0
#[[probes.filters]]
#name = "Bar"
#pattern = "456"
#count = 0
[[probes]]
address = "tcp://127.0.0.1:5556"
mode = "zmq"
name = "Probe 2"
count = 0
