allow-branch = [
    "main"
]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = true
publish = false
verify = true
owners = []
push = true
push-options = []
consolidate-commits = false
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pre-release-replacements = []
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
tag = true
enable-features = []
enable-all-features = false
dependent-version = "upgrade"
metadata = "optional"
